# Generated by Django 5.1 on 2024-08-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ventas_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('id_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='backend_ventas_api.customer')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='backend_ventas_api.user')),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_units', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('id_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend_ventas_api.supplier')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='backend_ventas_api.product')),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='backend_ventas_api.sale')),
            ],
            options={
                'db_table': 'sale_details',
                'constraints': [models.UniqueConstraint(fields=('id_sale', 'id_product'), name='unique_product_sale')],
                'unique_together': {('id_sale', 'id_product')},
            },
        ),
    ]
