# Generated by Django 5.1 on 2024-08-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ventas_api', '0002_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
