# Generated by Django 5.1 on 2024-08-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ventas_api', '0002_remove_customer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='nit',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
