# Generated by Django 5.1 on 2024-08-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ventas_api', '0003_supplier_created_at_supplier_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_usuario',
            new_name='id_user',
        ),
    ]
