# Generated by Django 5.1 on 2024-08-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ventas_api', '0003_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
