# Generated by Django 5.1 on 2024-08-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ventas_api', '0004_rename_id_usuario_user_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_sale_detail',
        ),
        migrations.AddField(
            model_name='saledetail',
            name='id_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='backend_ventas_api.sale'),
            preserve_default=False,
        ),
    ]
