from .customer_model import Customer
from .document_type_model import DocumentType
from .role_model import Role
from .user_model import User
from .UserRole_model import UserRole
from .supplier_model import Supplier
from .product_model import Product
from .sale_model import Sale
from .sale_detail_model import SaleDetail
